name: Hourly Deploy to Vercel

on:
  schedule:
    - cron: '0 * * * *' # 매 시간마다 실행 (UTC 기준)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
